export const links = {
  email: 'mailto:vinicius.padilha.br@gmail.com',
  github: 'https://github.com/padilhavinicius',
  linkedin: 'https://www.linkedin.com/in/viniciuspadilha/',
}

export const content = {
  pt: {
    nav: ['Início', 'Stack', 'Sobre', 'Experiência', 'Trabalhos', 'Contato'],
    availability: 'Aberto a conexões e novas oportunidades',
    eyebrow: 'OLÁ, EU SOU VINÍCIUS PADILHA',
    heroTitle: ['Construindo', 'software', 'que faz a diferença.'],
    heroDescription: 'Desenvolvedor Frontend Sênior com mais de 10 anos de experiência criando produtos web e mobile escaláveis. Hoje, conecto arquitetura de interfaces, visão de produto e desenvolvimento assistido por IA.',
    heroPrimary: 'Vamos conversar',
    heroSecondary: 'Meu trabalho',
    heroAside: 'FRONTEND  /  FULL STACK  /  AI',
    years: 'anos criando produtos digitais',
    experienceLabel: 'EXPERIÊNCIA DESDE 2016',
    scroll: 'DESLIZE PARA EXPLORAR',
    stackKicker: '01 / FERRAMENTAS',
    stackTitle: 'Tecnologia com intenção.',
    stackIntro: 'As ferramentas mudam. O foco permanece: construir experiências sólidas, acessíveis e fáceis de evoluir.',
    stackGroups: [
      { title: 'Interfaces & mobile', tags: ['React', 'React Native', 'Angular', 'Next.js', 'TypeScript', 'Tailwind CSS'] },
      { title: 'Arquitetura & produto', tags: ['Design Systems', 'Monorepos', 'Micro Frontends', 'REST / GraphQL', 'Performance', 'Acessibilidade'] },
      { title: 'Além da interface', tags: ['Node.js', 'PostgreSQL', 'CI/CD', 'AI-assisted development', 'Observabilidade'] },
    ],
    aboutKicker: '02 / SOBRE MIM',
    aboutTitle: 'Boas interfaces começam com boas decisões.',
    aboutParagraphs: [
      'Sou Vinícius, desenvolvedor de software morando atualmente no Brasil. Desde 2016, ajudo equipes a transformar problemas complexos em experiências digitais claras, rápidas e escaláveis.',
      'Minha base é frontend: React, Angular e React Native. Ao longo do caminho, liderei decisões técnicas, construí bibliotecas de componentes, integrei serviços e trabalhei lado a lado com produto, design e backend.',
      'Agora amplio minha atuação para o full stack e aplico IA de forma prática no desenvolvimento, com atenção à qualidade do código e ao resultado para quem usa o produto.',
    ],
    aboutTags: ['Curiosidade técnica', 'Colaboração', 'Visão de produto'],
    experienceKicker: '03 / TRAJETÓRIA',
    experienceTitle: 'Experiência que vira produto.',
    experienceIntro: 'Uma trajetória em produtos digitais, plataformas e experiências de alto impacto.',
    jobs: [
      { company: 'Quartile', role: 'Senior Frontend Developer · Portal Interface', period: 'OUT 2025 — ATUAL', detail: 'Evolução do portal em Angular, incluindo fluxos de enriquecimento de catálogos com IA, otimização de listings e correspondência de produtos entre canais. Manutenção da biblioteca de componentes e colaboração com backend em contratos e soluções.', tags: ['Angular', 'TypeScript', 'Playwright', 'IA'] },
      {
        company: 'L2', role: 'Frontend Tech Lead', rolePeriod: 'abr 2023 — out 2025', period: 'ABR 2021 — OUT 2025',
        detail: 'Liderança da equipe frontend, apoio na distribuição de tarefas e planejamento de projetos, além de decisões técnicas em interfaces e design systems.',
        previousRoles: [{ role: 'Senior Frontend Developer', period: 'abr 2021 — abr 2023', detail: 'Desenvolvimento de aplicações web e mobile para clientes de setores diversos.' }],
        tags: ['React', 'Next.js', 'Liderança técnica'],
      },
      { company: 'CWI Software', role: 'Frontend Developer', period: 'MAR 2020 — ABR 2021', detail: 'Desenvolvimento de aplicações web e mobile para clientes do varejo.', tags: ['React', 'Web', 'Mobile'] },
      {
        company: 'RCA Digital', role: 'Frontend Developer', rolePeriod: 'fev 2017 — mar 2020', period: 'FEV 2016 — MAR 2020',
        detail: 'Desenvolvimento de aplicações web e mobile para clientes do setor financeiro.',
        previousRoles: [{ role: 'Frontend Intern', period: 'fev 2016 — fev 2017', detail: 'Desenvolvimento de landing pages responsivas e peças de email marketing.' }],
        tags: ['React', 'Web', 'Mobile'],
      },
    ],
    workKicker: '04 / EM FOCO',
    workTitle: 'Problemas que gosto de resolver.',
    workIntro: 'Algumas frentes que representam meu trabalho, da estratégia à implementação.',
    work: [
      { number: '01', title: 'Plataformas de retail media', description: 'Interfaces para fluxos de catálogo, SEO e matching de produtos em múltiplos canais, com IA aplicada ao trabalho diário.', tags: ['Angular', 'IA', 'E-commerce'] },
      { number: '02', title: 'Experiências mobile', description: 'Produtos em React Native e Expo, com atenção à fluidez, integração e consistência entre telas.', tags: ['React Native', 'Expo', 'Mobile'] },
      { number: '03', title: 'Sistemas de design & arquitetura', description: 'Componentes compartilhados, tokens e estruturas de frontend que ajudam equipes a entregar com consistência.', tags: ['React', 'TypeScript', 'Design Systems'] },
    ],
    contactKicker: '05 / CONTATO',
    contactTitle: 'Vamos construir algo novo juntos?',
    contactText: 'Gosto de conversar sobre engenharia frontend, produtos digitais, colaboração entre times e novos desafios.',
    contactPrimary: 'Enviar um e-mail',
    contactSecondary: 'LinkedIn',
    themeLabel: 'Alternar tema',
    languageLabel: 'Idioma',
    openNew: 'Abre em nova aba',
  },
  en: {
    nav: ['Home', 'Stack', 'About', 'Experience', 'Work', 'Contact'],
    availability: 'Open to connections and new opportunities',
    eyebrow: "HI, I'M VINÍCIUS PADILHA",
    heroTitle: ['Building', 'software', 'that makes a difference.'],
    heroDescription: 'Senior Frontend Developer with 10+ years of experience building scalable web and mobile products. Today, I bring together interface architecture, product thinking, and AI-assisted development.',
    heroPrimary: "Let's talk",
    heroSecondary: 'My work',
    heroAside: 'FRONTEND  /  FULL STACK  /  AI',
    years: 'years building digital products',
    experienceLabel: 'BUILDING SINCE 2016',
    scroll: 'SCROLL TO EXPLORE',
    stackKicker: '01 / TOOLKIT',
    stackTitle: 'Technology with purpose.',
    stackIntro: 'Tools change. The focus stays the same: build reliable, accessible experiences that are easy to evolve.',
    stackGroups: [
      { title: 'Interfaces & mobile', tags: ['React', 'React Native', 'Angular', 'Next.js', 'TypeScript', 'Tailwind CSS'] },
      { title: 'Architecture & product', tags: ['Design Systems', 'Monorepos', 'Micro Frontends', 'REST / GraphQL', 'Performance', 'Accessibility'] },
      { title: 'Beyond the interface', tags: ['Node.js', 'PostgreSQL', 'CI/CD', 'AI-assisted development', 'Observability'] },
    ],
    aboutKicker: '02 / ABOUT ME',
    aboutTitle: 'Great interfaces start with good decisions.',
    aboutParagraphs: [
      "I'm Vinícius, a software developer currently living in Brazil. Since 2016, I've helped teams turn complex problems into clear, fast, and scalable digital experiences.",
      "Frontend is my foundation: React, Angular, and React Native. Along the way, I've led technical decisions, built component libraries, integrated services, and worked closely with product, design, and backend teams.",
      "I'm now expanding my work into full-stack development and putting AI to practical use in development, while keeping code quality and user outcomes in focus.",
    ],
    aboutTags: ['Technical curiosity', 'Collaboration', 'Product thinking'],
    experienceKicker: '03 / JOURNEY',
    experienceTitle: 'Experience turned into product.',
    experienceIntro: 'A career across digital products, platforms, and meaningful user experiences.',
    jobs: [
      { company: 'Quartile', role: 'Senior Frontend Developer · Portal Interface', period: 'OCT 2025 — PRESENT', detail: 'Evolving an Angular portal with AI catalog enrichment, listing optimization, and cross-channel product matching. Maintaining the component library and collaborating with backend on contracts and solutions.', tags: ['Angular', 'TypeScript', 'Playwright', 'AI'] },
      {
        company: 'L2', role: 'Frontend Tech Lead', rolePeriod: 'Apr 2023 — Oct 2025', period: 'APR 2021 — OCT 2025',
        detail: 'Led the frontend team, supported task assignment and project planning, and made technical decisions for interfaces and design systems.',
        previousRoles: [{ role: 'Senior Frontend Developer', period: 'Apr 2021 — Apr 2023', detail: 'Developed web and mobile applications for clients across different industries.' }],
        tags: ['React', 'Next.js', 'Technical leadership'],
      },
      { company: 'CWI Software', role: 'Frontend Developer', period: 'MAR 2020 — APR 2021', detail: 'Developed web and mobile applications for retail clients.', tags: ['React', 'Web', 'Mobile'] },
      {
        company: 'RCA Digital', role: 'Frontend Developer', rolePeriod: 'Feb 2017 — Mar 2020', period: 'FEB 2016 — MAR 2020',
        detail: 'Developed web and mobile applications for clients in the financial sector.',
        previousRoles: [{ role: 'Frontend Intern', period: 'Feb 2016 — Feb 2017', detail: 'Built responsive landing pages and email marketing assets.' }],
        tags: ['React', 'Web', 'Mobile'],
      },
    ],
    workKicker: '04 / SELECTED FOCUS',
    workTitle: 'Problems I like solving.',
    workIntro: 'A few areas that represent my work, from strategy to implementation.',
    work: [
      { number: '01', title: 'Retail media platforms', description: 'Interfaces for catalog workflows, SEO, and cross-channel product matching, with AI applied to day-to-day development.', tags: ['Angular', 'AI', 'E-commerce'] },
      { number: '02', title: 'Mobile experiences', description: 'Products built with React Native and Expo, designed for smooth interactions, integration, and consistency.', tags: ['React Native', 'Expo', 'Mobile'] },
      { number: '03', title: 'Design systems & architecture', description: 'Shared components, tokens, and frontend foundations that help teams ship consistently.', tags: ['React', 'TypeScript', 'Design Systems'] },
    ],
    contactKicker: '05 / CONTACT',
    contactTitle: "Let's build something new together?",
    contactText: 'I enjoy conversations about frontend engineering, digital products, cross-team collaboration, and new challenges.',
    contactPrimary: 'Send an email',
    contactSecondary: 'LinkedIn',
    themeLabel: 'Toggle theme',
    languageLabel: 'Language',
    openNew: 'Opens in a new tab',
  },
}
